package healthcalc;

public enum BMICategory {

    SEVERE_THINNESS,
    MODERATE_THINNESS,
    MILD_THINNESS,
    NORMAL_WEIGHT,
    OVERWEIGHT,
    OBESE_CLASS_I,
    OBESE_CLASS_II,
    OBESE_CLASS_III
}
